/** Named aliases over the generated OpenAPI types (`types.ts`, from backend/openapi.json). */
import type { components } from './types'

type S = components['schemas']

export type AssignmentOut = S['AssignmentOut']
export type ViolationOut = S['ViolationOut']
export type CoverageGapOut = S['CoverageGapOut']
export type HourShortfallOut = S['HourShortfallOut']
export type CostsOut = S['CostsOut']
export type ShiftCostOut = S['ShiftCostOut']
export type WorkerRefOut = S['WorkerRefOut']
export type GenerateOutcomeOut = S['GenerateOutcomeOut']
export type SaveRequest = S['SaveRequest']
export type SaveResponseOut = S['SaveResponseOut']
export type RosterOut = S['RosterOut']
export type Shift = AssignmentOut['shift']
export type Role = AssignmentOut['role']
export type ViolationCode = ViolationOut['code']

export type WorkerOut = S['WorkerOut']
export type WorkerDetailOut = S['WorkerDetailOut']
export type WorkerCreate = S['WorkerCreate']
export type WorkerPatch = S['WorkerPatch']
export type WorkerUpdateOut = S['WorkerUpdateOut']
export type WorkerStatus = WorkerOut['status']
export type ContractOut = S['ContractOut']
export type ContractsOut = S['ContractsOut']
export type ContractInput = S['ContractInput']
export type ContractPreviewOut = S['ContractPreviewOut']
export type ContractApplyOut = S['ContractApplyOut']
export type AffectedRosterOut = S['AffectedRosterOut']
export type LockedViolationOut = S['LockedViolationOut']
export type FieldChangeOut = S['FieldChangeOut']
