/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Meta */
        get: operations["get_meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CsvAliasesOut
         * @description P14 documented header and value aliases.
         */
        CsvAliasesOut: {
            /** Header Aliases */
            header_aliases: {
                [key: string]: string[];
            };
            /** Role Aliases */
            role_aliases: {
                [key: string]: string[];
            };
            /** Status Aliases */
            status_aliases: {
                [key: string]: string[];
            };
        };
        /** DemandEntry */
        DemandEntry: {
            /**
             * Shift
             * @enum {string}
             */
            shift: "A" | "B" | "C";
            /**
             * Role
             * @enum {string}
             */
            role: "GENERAL_GUARD" | "SCREENER" | "SUPERVISOR";
            /** Headcount */
            headcount: number;
        };
        /** MetaOut */
        MetaOut: {
            /** Shifts */
            shifts: ("A" | "B" | "C")[];
            /** Roles */
            roles: ("GENERAL_GUARD" | "SCREENER" | "SUPERVISOR")[];
            /** Demand */
            demand: components["schemas"]["DemandEntry"][];
            csv_aliases: components["schemas"]["CsvAliasesOut"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetaOut"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
