"""schema

Revision ID: f64a67d5168f
Revises: 
Create Date: 2026-09-29 00:06:42.071609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f64a67d5168f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('app_role', sa.String(), nullable=False),
    sa.CheckConstraint("app_role IN ('PLANNER', 'MANAGER')", name='ck_users_app_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('national_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("national_id ~ '^[0-9]{9}$'", name='ck_workers_national_id_format'),
    sa.CheckConstraint("role IN ('GENERAL_GUARD', 'SCREENER', 'SUPERVISOR')", name='ck_workers_role'),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name='ck_workers_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('national_id')
    )
    op.create_index('ix_workers_status_role', 'workers', ['status', 'role'], unique=False)
    op.create_table('csv_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(), server_default='PENDING', nullable=False),
    sa.Column('preview', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('PENDING', 'CONFIRMED')", name='ck_csv_imports_status'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rosters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), server_default='DRAFT', nullable=False),
    sa.Column('forbid_adjacent_shifts', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('generation_meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT', 'APPROVED')", name='ck_rosters_status'),
    sa.CheckConstraint('EXTRACT(DAY FROM month) = 1', name='ck_rosters_month_day1'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month', name='uq_rosters_month')
    )
    op.create_table('worker_field_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('old_value', sa.String(), nullable=False),
    sa.Column('new_value', sa.String(), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.CheckConstraint("field IN ('STATUS', 'ROLE')", name='ck_worker_field_history_field'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_worker_field_history_worker_field_effective', 'worker_field_history', ['worker_id', 'field', sa.literal_column('effective_at DESC')], unique=False)
    op.create_table('contract_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('effective_month', sa.Date(), nullable=False),
    sa.Column('hourly_rate_ils', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_hours', sa.Integer(), nullable=False),
    sa.Column('max_hours', sa.Integer(), nullable=False),
    sa.Column('availability', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('import_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("source IN ('UI', 'CSV')", name='ck_contract_versions_source'),
    sa.CheckConstraint('0 <= min_hours AND min_hours <= max_hours AND max_hours <= 744', name='ck_contract_versions_hours'),
    sa.CheckConstraint('EXTRACT(DAY FROM effective_month) = 1', name='ck_contract_versions_month_day1'),
    sa.CheckConstraint('hourly_rate_ils > 0', name='ck_contract_versions_rate_positive'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['import_id'], ['csv_imports.id'], ),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('worker_id', 'version_no', name='uq_contract_versions_worker_version')
    )
    op.create_index('ix_contract_versions_worker_effective_version', 'contract_versions', ['worker_id', sa.literal_column('effective_month DESC'), sa.literal_column('version_no DESC')], unique=False)
    op.create_table('roster_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('roster_version', sa.Integer(), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by', sa.Integer(), nullable=True),
    sa.Column('revoke_cause', sa.String(), nullable=True),
    sa.Column('revoke_ref', sa.String(), nullable=True),
    sa.CheckConstraint("revoke_cause IN ('EDIT', 'REGENERATE', 'CONTRACT_CHANGE', 'WORKER_CHANGE') OR revoke_cause IS NULL", name='ck_roster_approvals_revoke_cause'),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['revoked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['roster_id'], ['rosters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_roster_approvals_roster_approved_at', 'roster_approvals', ['roster_id', sa.literal_column('approved_at DESC')], unique=False)
    op.create_table('roster_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['roster_id'], ['rosters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('roster_id', 'worker_id', 'date', 'shift', name='uq_roster_assignments_roster_worker_date_shift')
    )
    op.create_index('ix_roster_assignments_roster_date_shift', 'roster_assignments', ['roster_id', 'date', 'shift'], unique=False)
    op.create_index('ix_roster_assignments_worker', 'roster_assignments', ['worker_id'], unique=False)
    # ### end Alembic commands ###

    # Immutability triggers (§3): contract_versions and worker_field_history
    # are insert-only. One shared trigger function raises on UPDATE/DELETE.
    op.execute(
        """
        CREATE FUNCTION reject_update_delete() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION '% is insert-only; % is not allowed on %',
                TG_TABLE_NAME, TG_OP, TG_TABLE_NAME;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_contract_versions_immutable
        BEFORE UPDATE OR DELETE ON contract_versions
        FOR EACH ROW EXECUTE FUNCTION reject_update_delete();
        """
    )
    op.execute(
        """
        CREATE TRIGGER trg_worker_field_history_immutable
        BEFORE UPDATE OR DELETE ON worker_field_history
        FOR EACH ROW EXECUTE FUNCTION reject_update_delete();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_worker_field_history_immutable ON worker_field_history;")
    op.execute("DROP TRIGGER IF EXISTS trg_contract_versions_immutable ON contract_versions;")
    op.execute("DROP FUNCTION IF EXISTS reject_update_delete();")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_roster_assignments_worker', table_name='roster_assignments')
    op.drop_index('ix_roster_assignments_roster_date_shift', table_name='roster_assignments')
    op.drop_table('roster_assignments')
    op.drop_index('ix_roster_approvals_roster_approved_at', table_name='roster_approvals')
    op.drop_table('roster_approvals')
    op.drop_index('ix_contract_versions_worker_effective_version', table_name='contract_versions')
    op.drop_table('contract_versions')
    op.drop_index('ix_worker_field_history_worker_field_effective', table_name='worker_field_history')
    op.drop_table('worker_field_history')
    op.drop_table('rosters')
    op.drop_table('csv_imports')
    op.drop_index('ix_workers_status_role', table_name='workers')
    op.drop_table('workers')
    op.drop_table('users')
    # ### end Alembic commands ###
